import type { Dictionary } from "@/lib/i18n/get-dictionary";

export type CheckoutLabels = {
  title: string;
  productsInOrder: string;
  itemsOne: string;
  itemsMany: string;
  previousItem: string;
  nextItem: string;
  removeItem: string;
  contactInformation: string;
  shippingAddress: string;
  paymentMethod: string;
  orderSummary: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  address: string;
  floor: string;
  intercomCode: string;
  phonePlaceholder: string;
  addressPlaceholder: string;
  floorPlaceholder: string;
  intercomCodePlaceholder: string;
  openMap: string;
  mapTitle: string;
  mapHint: string;
  mapConfirm: string;
  mapCancel: string;
  mapResolving: string;
  enterDeliveryAddress: string;
  calculatingDelivery: string;
  scheduleTitle: string;
  schedulePickDate: string;
  schedulePickTime: string;
  scheduleNoSlots: string;
  schedulePrevMonth: string;
  scheduleNextMonth: string;
  selectDeliverySlot: string;
  cashChangeTitle: string;
  cashChangeHint: string;
  cashChangeNone: string;
  cashChangeDue: string;
  cashOnDelivery: string;
  cashOnDeliveryDescription: string;
  cashShort: string;
  idram: string;
  idramDescription: string;
  card: string;
  cardDescription: string;
  couponTitle: string;
  couponPlaceholder: string;
  couponApply: string;
  couponApplying: string;
  giftCardTitle: string;
  giftCardPlaceholder: string;
  giftCardApply: string;
  giftCardApplying: string;
  giftCardInitial: string;
  giftCardUsed: string;
  giftCardRemaining: string;
  giftCardPayable: string;
  giftCardApplied: string;
  bonusTitle: string;
  bonusAvailable: string;
  bonusUse: string;
  bonusAmount: string;
  bonusUseMax: string;
  bonusApplied: string;
  bonusEarn: string;
  discount: string;
  subtotal: string;
  shipping: string;
  change: string;
  total: string;
  placeOrder: string;
  processing: string;
  continueShopping: string;
  cartEmpty: string;
  groupPrepaidTitle: string;
  groupPrepaidHint: string;
  groupPrepaidOthersPaid: string;
  groupPrepaidYouPay: string;
};

/** Maps checkout dictionary copy onto CheckoutForm labels. */
export function checkoutFormLabels(
  copy: Dictionary["checkout"],
): CheckoutLabels {
  return {
    title: copy.title,
    productsInOrder: copy.productsInOrder,
    itemsOne: copy.itemsOne,
    itemsMany: copy.itemsMany,
    previousItem: copy.previousItem,
    nextItem: copy.nextItem,
    removeItem: copy.removeItem,
    contactInformation: copy.contactInformation,
    shippingAddress: copy.shippingAddress,
    paymentMethod: copy.paymentMethod,
    orderSummary: copy.orderSummary,
    firstName: copy.form.firstName,
    lastName: copy.form.lastName,
    email: copy.form.email,
    phone: copy.form.phone,
    address: copy.form.address,
    floor: copy.form.floor,
    intercomCode: copy.form.intercomCode,
    phonePlaceholder: copy.placeholders.phone,
    addressPlaceholder: copy.placeholders.address,
    floorPlaceholder: copy.placeholders.floor,
    intercomCodePlaceholder: copy.placeholders.intercomCode,
    openMap: copy.map.openMap,
    mapTitle: copy.map.title,
    mapHint: copy.map.hint,
    mapConfirm: copy.map.confirm,
    mapCancel: copy.map.cancel,
    mapResolving: copy.map.resolving,
    enterDeliveryAddress: copy.shipping.enterDeliveryAddress,
    calculatingDelivery: copy.shipping.calculatingDelivery,
    scheduleTitle: copy.schedule.title,
    schedulePickDate: copy.schedule.pickDate,
    schedulePickTime: copy.schedule.pickTime,
    scheduleNoSlots: copy.schedule.noSlots,
    schedulePrevMonth: copy.schedule.prevMonth,
    scheduleNextMonth: copy.schedule.nextMonth,
    selectDeliverySlot: copy.schedule.selectSlot,
    cashChangeTitle: copy.cashChange.title,
    cashChangeHint: copy.cashChange.hint,
    cashChangeNone: copy.cashChange.none,
    cashChangeDue: copy.cashChange.due,
    cashOnDelivery: copy.payment.cashOnDelivery,
    cashOnDeliveryDescription: copy.payment.cashOnDeliveryDescription,
    cashShort: copy.payment.cashShort,
    idram: copy.payment.idram,
    idramDescription: copy.payment.idramDescription,
    card: copy.payment.card,
    cardDescription: copy.payment.cardDescription,
    couponTitle: copy.coupon.title,
    couponPlaceholder: copy.coupon.placeholder,
    couponApply: copy.coupon.apply,
    couponApplying: copy.coupon.applying,
    giftCardTitle: copy.giftCard.title,
    giftCardPlaceholder: copy.giftCard.placeholder,
    giftCardApply: copy.giftCard.apply,
    giftCardApplying: copy.giftCard.applying,
    giftCardInitial: copy.giftCard.initial,
    giftCardUsed: copy.giftCard.used,
    giftCardRemaining: copy.giftCard.remaining,
    giftCardPayable: copy.giftCard.payable,
    giftCardApplied: copy.giftCard.applied,
    bonusTitle: copy.bonus.title,
    bonusAvailable: copy.bonus.available,
    bonusUse: copy.bonus.use,
    bonusAmount: copy.bonus.amount,
    bonusUseMax: copy.bonus.useMax,
    bonusApplied: copy.bonus.applied,
    bonusEarn: copy.bonus.earn,
    discount: copy.summary.discount,
    subtotal: copy.summary.subtotal,
    shipping: copy.summary.shipping,
    change: copy.summary.change,
    total: copy.summary.total,
    placeOrder: copy.buttons.placeOrder,
    processing: copy.buttons.processing,
    continueShopping: copy.buttons.continueShopping,
    cartEmpty: copy.errors.cartEmpty,
    groupPrepaidTitle: copy.groupPrepaid.title,
    groupPrepaidHint: copy.groupPrepaid.hint,
    groupPrepaidOthersPaid: copy.groupPrepaid.othersPaid,
    groupPrepaidYouPay: copy.groupPrepaid.youPay,
  };
}
